In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ipma = pd.read_excel("Dados IPMA Bivalves- Chumbo.xlsx")

In [3]:
ipma

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
1,60/23,2023-01-24,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
2,50/23,2023-01-22,L5a,Praia dos Coxos,Lapa,0.1
3,30/23,2023-01-12,L6,Praia da Samoqueira,Lapa,0.22
4,21/23,2023-01-10,ETJ1,Vagem da Cana Verde,Ostra-portuguesa,0.26
...,...,...,...,...,...,...
2024,13189,2014-11-05,ESD2,Abul,Ostra-portuguesa,0.34
2025,13166,2014-10-29,EMR,Casa Branca,Ostra-portuguesa,0.28
2026,13156,2014-10-27,RIAV3,Espinheiro,Berbigão,0.41
2027,13140,2014-10-22,ESD2,Abul,Ostra-portuguesa,0.09
2028,13041,2014-10-06,ETJ,Samouco,Lambujinha,2.2

In [4]:
ipma.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2029 entries, 0 to 2028
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nº Amostra        2029 non-null   object
 1   Data de colheita  2029 non-null   datetime64[ns]
 2   Zona de
Produção  2025 non-null   object
 3   Local             2029 non-null   object
 4   Espécie           2029 non-null   object
 5   Pb
(mg/kg)        2029 non-null   object
dtypes: datetime64[ns](1), object(5)
memory usage: 95.2+ KB

# Valores NaN

In [5]:
ipma.isnull().sum()

Nº Amostra           0
Data de colheita     0
Zona de\nProdução    4
Local                0
Espécie              0
Pb\n(mg/kg)          0
dtype: int64

# Limpar dados com "LD"

Dados da Coluna "Pb\n(mg/kg)" que contenham a string "LD"

In [6]:
#Filtrar Dados que queremos limpar
limparLD = ipma[ipma["Pb\n(mg/kg)"].str.contains("LD", regex = False, na = False)]
limparLD

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
368,981/21,2021-10-21,EMR,Roncanito,Ostra-portuguesa,LD
393,942/21,2021-10-13,OLH4,Garganta,Amêijoa-boa,LD
396,927/21,2021-10-12,L2,Leça da Palmeira,Ouriço-do-mar,LD
397,928/21,2021-10-12,L1,Carreço,Ouriço-do-mar,LD

In [7]:
# Eliminar dados que queremos limpar
ipma2 = ipma.drop(limparLD.index)
ipma2.head()

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
1,60/23,2023-01-24,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
2,50/23,2023-01-22,L5a,Praia dos Coxos,Lapa,0.1
3,30/23,2023-01-12,L6,Praia da Samoqueira,Lapa,0.22
4,21/23,2023-01-10,ETJ1,Vagem da Cana Verde,Ostra-portuguesa,0.26

In [8]:
#Verificar se dados foram eliminados
ipma2[ipma2["Pb\n(mg/kg)"].str.contains("LD", regex = False, na = False)]

Empty DataFrame
Columns: [Nº Amostra, Data de colheita, Zona de
Produção, Local, Espécie, Pb
(mg/kg)]
Index: []

# Ánalise Explorátoria (Para Dados Categóricos)

1 - Ver Espécies:

In [9]:
ipma2["Espécie"].value_counts()

Lapa                      251
Mexilhão                  227
Ostra-portuguesa          221
Amêijoa-boa               204
Ostra-japonesa/gigante    167
Lambujinha                155
Amêijoa-japonesa          153
Berbigão                  137
Amêijoa-branca             71
Longueirão                 66
Conquilha                  53
Amêijoa-macha              49
Ostra-gigante              46
Ouriço-do-mar              43
Ostra-plana                32
Castanhola                 28
Ostra-gigante/japonesa     21
Pé-de-burro                15
Amêijola                   15
Amêijoa-relógio            10
Ostra                       8
Canilha                     7
Longueirão-direito          6
Buzina                      5
Buzinas                     4
Amêijoa-asiática            4
Amêijoa-cão                 4
Pé-de-burrinho              4
Vieira                      3
Pé-de burrinho              2
Taralhão                    2
Zamburinha                  2
Ostra-japonesa              2
Búzio                       1
Amêjoa-boa                  1
Amêija-japonesa             1
Mexihão                     1
Leque                       1
Burrié                      1
Navalha                     1
Ostra-gigas                 1
Name: Espécie, dtype: int64

Eliminar dados Categóricos que não Interessam:
    Lapa, Buzinas, Canilha, Ouriço do mar, Buzina, Burrié,

In [10]:
#Limpar dados da Coluna "Espécie" = "Lapa"
lapa=ipma2[ipma2["Espécie"] == "Lapa"]
lapa

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
2,50/23,2023-01-22,L5a,Praia dos Coxos,Lapa,0.1
3,30/23,2023-01-12,L6,Praia da Samoqueira,Lapa,0.22
6,1317/22,2022-12-18,L5a,Praia dos Coxos,Lapa,0.28
7,1294/22,2022-12-12,L6,Praia da Samoqueira,Lapa,0.28
14,1186/22,2022-11-07,L5a,Praia dos Coxos,Lapa,0.11
...,...,...,...,...,...,...
1656,16602,2017-04-11,L7A,Aljezur,Lapa,0.51
1657,16603,2017-04-11,L4,Leirosa,Lapa,0.34
1658,16604,2017-04-11,L4,Leirosa,Lapa,0.34
1659,16605,2017-04-11,L6,Praia da Samoqueira,Lapa,0.24
1701,16484,2017-03-09,L6,Praia da Samoqueira,Lapa,0.3

In [11]:
ipma3 = ipma2.drop(lapa.index)
ipma3

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
1,60/23,2023-01-24,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
4,21/23,2023-01-10,ETJ1,Vagem da Cana Verde,Ostra-portuguesa,0.26
5,1324/22,2022-12-19,EMN ZN,Ponto 3 N,Berbigão,0.19
8,1295/22,2022-12-12,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
...,...,...,...,...,...,...
2024,13189,2014-11-05,ESD2,Abul,Ostra-portuguesa,0.34
2025,13166,2014-10-29,EMR,Casa Branca,Ostra-portuguesa,0.28
2026,13156,2014-10-27,RIAV3,Espinheiro,Berbigão,0.41
2027,13140,2014-10-22,ESD2,Abul,Ostra-portuguesa,0.09
2028,13041,2014-10-06,ETJ,Samouco,Lambujinha,2.2

In [12]:
#Limpar dados da Coluna "Espécie" = "Buzinas"
buzinas=ipma3[ipma3["Espécie"] == "Buzinas"]
buzinas

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
331,1213/21,2021-12-13,L7c2,Armação de Pêra,Buzinas,"< 0,02"
332,1177/21,2021-12-07,L7c1,Offshore,Buzinas,"< 0,02"
341,1148/21,2021-11-30,L7c2,Armação de Pera,Buzinas,0.02
343,1140/21,2021-11-23,L7c1,Offshore,Buzinas,"< 0,02"

In [13]:
ipma4 = ipma3.drop(buzinas.index)
ipma4

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
1,60/23,2023-01-24,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
4,21/23,2023-01-10,ETJ1,Vagem da Cana Verde,Ostra-portuguesa,0.26
5,1324/22,2022-12-19,EMN ZN,Ponto 3 N,Berbigão,0.19
8,1295/22,2022-12-12,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
...,...,...,...,...,...,...
2024,13189,2014-11-05,ESD2,Abul,Ostra-portuguesa,0.34
2025,13166,2014-10-29,EMR,Casa Branca,Ostra-portuguesa,0.28
2026,13156,2014-10-27,RIAV3,Espinheiro,Berbigão,0.41
2027,13140,2014-10-22,ESD2,Abul,Ostra-portuguesa,0.09
2028,13041,2014-10-06,ETJ,Samouco,Lambujinha,2.2

In [14]:
#Limpar dados da Coluna "Espécie" = "Canilha"
canilha = ipma4[ipma4["Espécie"] == "Canilha"]
canilha

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
161,416/22,2022-05-04,L9,Praia do Barril,Canilha,0.29
296,101/22,2022-02-16,L9,Praia do Barril,Canilha,0.15
387,936/21,2021-10-13,L9,Praia do Barril,Canilha,0.15
422,860/21,2021-09-22,L9,Praia do Barril,Canilha,0.27
488,746/21,2021-08-31,L7c2,Albufeira/Portimão,Canilha,0.22
490,730/21,2021-08-25,L9,Praia do Barril,Canilha,0.14
501,652/21,2021-07-22,L9,Praia do Barril,Canilha,< 0.06

In [15]:
ipma5 = ipma4.drop(canilha.index)
ipma5

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
1,60/23,2023-01-24,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
4,21/23,2023-01-10,ETJ1,Vagem da Cana Verde,Ostra-portuguesa,0.26
5,1324/22,2022-12-19,EMN ZN,Ponto 3 N,Berbigão,0.19
8,1295/22,2022-12-12,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
...,...,...,...,...,...,...
2024,13189,2014-11-05,ESD2,Abul,Ostra-portuguesa,0.34
2025,13166,2014-10-29,EMR,Casa Branca,Ostra-portuguesa,0.28
2026,13156,2014-10-27,RIAV3,Espinheiro,Berbigão,0.41
2027,13140,2014-10-22,ESD2,Abul,Ostra-portuguesa,0.09
2028,13041,2014-10-06,ETJ,Samouco,Lambujinha,2.2

In [16]:
#Limpar dados da Coluna "Espécie" = "Ouriço-do-mar"
ouriço = ipma5[ipma5["Espécie"] == "Ouriço-do-mar"]
ouriço

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
1,60/23,2023-01-24,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
27,1059/22,2022-10-06,L7a,Portinho da Arrifana,Ouriço-do-mar,< 0.06
41,1049/22,2022-09-28,L1,Carreço,Ouriço-do-mar,< 0.06
48,1018/22,2022-09-26,L5a,Praia dos Coxos,Ouriço-do-mar,< 0.06
146,621/22,2022-06-19,L5a,Praia dos Coxos,Ouriço-do-mar,"< 0,06"
183,348/22,2022-04-26,L7a,Portinho da Arrifana,Ouriço-do-mar,"< 0,06"
214,285/22,2022-04-05,L1,Carreço,Ouriço-do-mar,"< 0,06"
215,286/22,2022-04-05,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
254,202/22,2022-03-20,L5a,Praia dos Coxos,Ouriço-do-mar,0.07
412,873/21,2021-09-27,L5a,Praia dos Coxos,Ouriço-do-mar,< 0.06
477,772/21,2021-09-07,L7a,Portinho da Arrifana,Ouriço-do-mar,< 0.06
509,639/21,2021-07-18,L5a,Praia dos Coxos,Ouriço-do-mar,0.11
596,258/21,2021-03-14,L5a,Praia dos Coxos,Ouriço-do-mar,0.06
608,244/21,2021-03-09,L7a,Aljezur - Arrifana,Ouriço-do-mar,"< 0,06"
639,194/21,2021-03-02,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
640,195/21,2021-03-02,L1,Carreço,Ouriço-do-mar,"< 0,02"
676,41/21,2021-01-17,L5a,Praia dos Coxos,Ouriço-do-mar,"< 0,06"
708,1227/20,2020-11-02,L5a,Praia dos Coxos,Ouriço-do-mar,0.5
792,722/20,2020-09-08,L7a,Portinho da Arrifana,Ouriço-do-mar,"< 0,02"
824,689/20,2020-09-01,L2,Leça da Palmeira,Ouriço-do-mar,0.02
825,690/20,2020-09-01,L1,Carreço,Ouriço-do-mar,0.02
879,345/20,2020-05-05,L7a,Aljezur,Ouriço-do-mar,0.07
910,251/20,2020-03-24,L1,Carreço,Ouriço-do-mar,"< 0,06"
911,252/20,2020-03-24,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
923,226/20,2020-03-11,L5a,Praia dos Coxos,Ouriço-do-mar,0.11
1108,19566,2019-09-17,L5a,Praia dos Coxos,Ouriço-do-mar,"< 0,06"
1151,19524,2019-09-03,L1,Carreço,Ouriço-do-mar,"< 0,02"
1152,19525,2019-09-03,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
1199,19185,2019-05-06,L5a,Praia dos Coxos,Ouriço-do-mar,"< 0,06"
1230,19067,2019-03-19,L1,Carreço,Ouriço-do-mar,"< 0,02"
1231,19068,2019-03-19,L2,Leça da Palmeira,Ouriço-do-mar,0.02
1235,19073,2019-03-19,L7a,Aljezur,Ouriço-do-mar,"< 0,06"
1297,18844,2019-01-08,L6,Praia da Costa do Norte,Ouriço-do-mar,"< 0,06"
1317,18528,2018-10-09,L1,Carreço,Ouriço-do-mar,"< 0,06"
1319,18531,2018-10-09,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
1449,17793,2018-03-22,L7A,Aljezur,Ouriço-do-mar,0.15
1457,17777,2018-03-20,L2,Leça da Palmeira,Ouriço-do-mar,0.07
1458,17778,2018-03-20,L1,Carreço,Ouriço-do-mar,0.06
1493,17735,2018-03-07,L5a,Praia dos Tombadoiros,Ouriço-do-mar,0.48
1523,17442,2017-11-21,L2,Leça da Palmeira,Ouriço-do-mar,"< 0,06"
1538,17267,2017-10-11,L7A,Aljezur,Ouriço-do-mar,0.23
1559,17151,2017-09-21,L5,Praia dos Tombadoiros,Ouriço-do-mar,0.09
1566,17140,2017-09-20,L1,Carreço,Ouriço-do-mar,0.08

In [17]:
ipma6 = ipma5.drop(ouriço.index)
ipma6

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
4,21/23,2023-01-10,ETJ1,Vagem da Cana Verde,Ostra-portuguesa,0.26
5,1324/22,2022-12-19,EMN ZN,Ponto 3 N,Berbigão,0.19
8,1295/22,2022-12-12,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
9,1282/22,2022-11-30,L7c2,Offshore MS1,Vieira,0.08
...,...,...,...,...,...,...
2024,13189,2014-11-05,ESD2,Abul,Ostra-portuguesa,0.34
2025,13166,2014-10-29,EMR,Casa Branca,Ostra-portuguesa,0.28
2026,13156,2014-10-27,RIAV3,Espinheiro,Berbigão,0.41
2027,13140,2014-10-22,ESD2,Abul,Ostra-portuguesa,0.09
2028,13041,2014-10-06,ETJ,Samouco,Lambujinha,2.2

In [18]:
#Limpar dados da Coluna "Espécie" = "Buzina"
buzina = ipma6[ipma6["Espécie"] == "Buzina"]
buzina

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
26,1058/22,2022-10-06,L8,Culatra,Buzina,< 0.02
150,505/22,2022-06-07,L7c1,Offshore 1,Buzina,0.02
152,486/22,2022-05-31,L7c2,Armação de Pêra,Buzina,0.02
423,861/21,2021-09-22,L9,Praia do Barril,Buzina,0.5
487,749/21,2021-09-02,L8,Culatra,Buzina,0.06

In [19]:
ipma7 = ipma6.drop(buzina.index)
ipma7

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
4,21/23,2023-01-10,ETJ1,Vagem da Cana Verde,Ostra-portuguesa,0.26
5,1324/22,2022-12-19,EMN ZN,Ponto 3 N,Berbigão,0.19
8,1295/22,2022-12-12,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
9,1282/22,2022-11-30,L7c2,Offshore MS1,Vieira,0.08
...,...,...,...,...,...,...
2024,13189,2014-11-05,ESD2,Abul,Ostra-portuguesa,0.34
2025,13166,2014-10-29,EMR,Casa Branca,Ostra-portuguesa,0.28
2026,13156,2014-10-27,RIAV3,Espinheiro,Berbigão,0.41
2027,13140,2014-10-22,ESD2,Abul,Ostra-portuguesa,0.09
2028,13041,2014-10-06,ETJ,Samouco,Lambujinha,2.2

In [20]:
#Limpar dados da Coluna "Espécie" = "Buzina"
burrie = ipma7[ipma7["Espécie"] == "Burrié"]
burrie

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
1081,19676,2019-10-15,ESD2,Carrasqueira,Burrié,0.06

In [21]:
ipma8 = ipma7.drop(burrie.index)
ipma8

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
4,21/23,2023-01-10,ETJ1,Vagem da Cana Verde,Ostra-portuguesa,0.26
5,1324/22,2022-12-19,EMN ZN,Ponto 3 N,Berbigão,0.19
8,1295/22,2022-12-12,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
9,1282/22,2022-11-30,L7c2,Offshore MS1,Vieira,0.08
...,...,...,...,...,...,...
2024,13189,2014-11-05,ESD2,Abul,Ostra-portuguesa,0.34
2025,13166,2014-10-29,EMR,Casa Branca,Ostra-portuguesa,0.28
2026,13156,2014-10-27,RIAV3,Espinheiro,Berbigão,0.41
2027,13140,2014-10-22,ESD2,Abul,Ostra-portuguesa,0.09
2028,13041,2014-10-06,ETJ,Samouco,Lambujinha,2.2

In [22]:
#Limpar dados da Coluna "Espécie" = "Búzio"
buzio= ipma8[ipma8["Espécie"] == "Búzio"]
buzio

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
358,1027/21,2021-11-03,OLH2,Fortaleza,Búzio,"< 0,06"

In [23]:
#Limpar dados da Coluna "Espécie" = "
ipma9 = ipma8.drop(buzio.index)
ipma9["Espécie"].value_counts()

Mexilhão                  227
Ostra-portuguesa          221
Amêijoa-boa               204
Ostra-japonesa/gigante    167
Lambujinha                155
Amêijoa-japonesa          153
Berbigão                  137
Amêijoa-branca             71
Longueirão                 66
Conquilha                  53
Amêijoa-macha              49
Ostra-gigante              46
Ostra-plana                32
Castanhola                 28
Ostra-gigante/japonesa     21
Pé-de-burro                15
Amêijola                   15
Amêijoa-relógio            10
Ostra                       8
Longueirão-direito          6
Amêijoa-cão                 4
Pé-de-burrinho              4
Amêijoa-asiática            4
Vieira                      3
Zamburinha                  2
Taralhão                    2
Pé-de burrinho              2
Ostra-japonesa              2
Navalha                     1
Amêija-japonesa             1
Leque                       1
Mexihão                     1
Amêjoa-boa                  1
Ostra-gigas                 1
Name: Espécie, dtype: int64

# Dados Duplicados

In [24]:
ipma9[ipma9.duplicated(["Nº Amostra", "Data de colheita", "Zona de\nProdução", "Local","Espécie", "Pb\n(mg/kg)"],keep=False)]

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
309,30/22,2022-01-18,ETJ1,Samouco,Lambujinha,2
310,30/22,2022-01-18,ETJ1,Samouco,Lambujinha,2
311,20/22,2022-01-17,LOB,Frente à Escola de Vela,Mexilhão,"< 0,06"
312,21/22,2022-01-17,LOB,Greijau,Amêijoa-macha,"< 0,06"
313,22/22,2022-01-17,LOB,Espichel,Amêijoa-relógio,0.74
314,23/22,2022-01-17,LOB,Espichel,Amêijoa-boa,0.02
315,24/22,2022-01-17,LOB,Espichel,Longueirão,"< 0,06"
316,25/22,2022-01-17,LOB,Espichel,Amêijoa-japonesa,"< 0,06"
317,26/22,2022-01-17,LOB,Espichel,Berbigão,0.14
318,20/22,2022-01-17,LOB,Frente à Escola de Vela,Mexilhão,"< 0,06"
319,21/22,2022-01-17,LOB,Greijau,Amêijoa-macha,"< 0,06"
320,22/22,2022-01-17,LOB,Espichel,Amêijoa-relógio,0.74
321,23/22,2022-01-17,LOB,Espichel,Amêijoa-boa,0.02
322,24/22,2022-01-17,LOB,Espichel,Longueirão,"< 0,06"
323,25/22,2022-01-17,LOB,Espichel,Amêijoa-japonesa,"< 0,06"
324,26/22,2022-01-17,LOB,Espichel,Berbigão,0.14
327,10/22,2022-01-11,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
328,10/22,2022-01-11,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
1927,14116,2015-07-22,ESD1 Esteiro da Marateca,Canal da Vaia,Ostra-portuguesa,0.13
1928,14116,2015-07-22,ESD1 Esteiro da Marateca,Canal da Vaia,Ostra-portuguesa,0.13
1930,14061,2015-07-09,ESD1 Esteiro da Marateca,Gambia,Ostra-portuguesa,0.1
1931,14061,2015-07-09,ESD1 Esteiro da Marateca,Gambia,Ostra-portuguesa,0.1
1932,13924,2015-06-18,EMR,Roncão/Casa Branca,Ostra-portuguesa,0.05
1933,13924,2015-06-18,EMR,Roncão/Casa Branca,Ostra-portuguesa,0.05
1934,13911,2015-06-17,ESD1 Esteiro da Marateca,Canal da Vaia,Ostra-portuguesa,0.1
1935,13911,2015-06-17,ESD1 Esteiro da Marateca,Canal da Vaia,Ostra-portuguesa,0.1
1936,13889,2015-06-16,ETJ,Samouco,Lambujinha,3
1937,13897,2015-06-16,ESD2 Canal de Alcácer,Casas Novas/Batalha,Ostra-portuguesa,0.13
1938,13889,2015-06-16,ETJ,Samouco,Lambujinha,3
1939,13897,2015-06-16,ESD2 Canal de Alcácer,Casas Novas/Batalha,Ostra-portuguesa,0.13
1940,13852,2015-06-02,ESD2 Canal de Alcácer,Casas Novas/Batalha,Ostra-portuguesa,0.11
1941,13852,2015-06-02,ESD2 Canal de Alcácer,Casas Novas/Batalha,Ostra-portuguesa,0.11
1942,13824,2015-05-20,EMR,Roncão/Casa Branca,Ostra-portuguesa,0.11
1943,13824,2015-05-20,EMR,Roncão/Casa Branca,Ostra-portuguesa,0.11
1944,13810,2015-05-19,ETJ,Samouco,Lambujinha,2.9
1945,13810,2015-05-19,ETJ,Samouco,Lambujinha,2.9
1946,13807,2015-05-18,ESD2 Canal de Alcácer,Casas Novas/Batalha,Ostra-portuguesa,0.12
1947,13807,2015-05-18,ESD2 Canal de Alcácer,Casas Novas/Batalha,Ostra-portuguesa,0.12
1948,13781,2015-05-14,ESD1 Esteiro da Marateca,Faralhão,Ostra-plana,0.08
1949,13782,2015-05-14,ESD1 Esteiro da Marateca,Faralhão,Ostra-portuguesa,0.12
1950,13781,2015-05-14,ESD1 Esteiro da Marateca,Faralhão,Ostra-plana,0.08
1951,13782,2015-05-14,ESD1 Esteiro da Marateca,Faralhão,Ostra-portuguesa,0.12
1952,13771,2015-05-13,ESD1 Esteiro da Marateca,Canal da Vaia,Ostra-portuguesa,0.18
1953,13771,2015-05-13,ESD1 Esteiro da Marateca,Canal da Vaia,Ostra-portuguesa,0.18

In [25]:
#Eliminar Dados Duplicados
ipma9.drop_duplicates(subset=["Nº Amostra","Data de colheita", "Zona de\nProdução", "Local","Espécie", "Pb\n(mg/kg)"], keep='first',inplace=True)

In [26]:
#Verificar se Duplicados foram apagados 
ipma9[ipma9.duplicated(["Nº Amostra", "Data de colheita", "Zona de\nProdução", "Local","Espécie", "Pb\n(mg/kg)"],keep=False)]

Empty DataFrame
Columns: [Nº Amostra, Data de colheita, Zona de
Produção, Local, Espécie, Pb
(mg/kg)]
Index: []

In [27]:
ipma9

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
4,21/23,2023-01-10,ETJ1,Vagem da Cana Verde,Ostra-portuguesa,0.26
5,1324/22,2022-12-19,EMN ZN,Ponto 3 N,Berbigão,0.19
8,1295/22,2022-12-12,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
9,1282/22,2022-11-30,L7c2,Offshore MS1,Vieira,0.08
...,...,...,...,...,...,...
2024,13189,2014-11-05,ESD2,Abul,Ostra-portuguesa,0.34
2025,13166,2014-10-29,EMR,Casa Branca,Ostra-portuguesa,0.28
2026,13156,2014-10-27,RIAV3,Espinheiro,Berbigão,0.41
2027,13140,2014-10-22,ESD2,Abul,Ostra-portuguesa,0.09
2028,13041,2014-10-06,ETJ,Samouco,Lambujinha,2.2

# Padronizar Dados

In [28]:
ipma9["Espécie"].value_counts()

Mexilhão                  226
Ostra-portuguesa          210
Amêijoa-boa               203
Ostra-japonesa/gigante    167
Lambujinha                152
Amêijoa-japonesa          152
Berbigão                  136
Amêijoa-branca             71
Longueirão                 65
Conquilha                  53
Amêijoa-macha              48
Ostra-gigante              46
Ostra-plana                31
Castanhola                 28
Ostra-gigante/japonesa     21
Pé-de-burro                15
Amêijola                   15
Amêijoa-relógio             9
Ostra                       8
Longueirão-direito          6
Amêijoa-cão                 4
Pé-de-burrinho              4
Amêijoa-asiática            4
Vieira                      3
Zamburinha                  2
Taralhão                    2
Pé-de burrinho              2
Ostra-japonesa              2
Navalha                     1
Amêija-japonesa             1
Leque                       1
Mexihão                     1
Amêjoa-boa                  1
Ostra-gigas                 1
Name: Espécie, dtype: int64

In [29]:
# Ostra-japonesa
ipma9.loc[ipma9["Espécie"].isin( ["Ostra-japonesa/gigante",
                                  "Ostra-gigante",
                                  "Ostra-gigante/japonesa",
                                  "Ostra-japonesa",
                                  "Ostra-gigas"] ) , "Espécie"] = "Ostra-japonesa"

In [30]:
ipma9["Espécie"].value_counts()

Ostra-japonesa        237
Mexilhão              226
Ostra-portuguesa      210
Amêijoa-boa           203
Lambujinha            152
Amêijoa-japonesa      152
Berbigão              136
Amêijoa-branca         71
Longueirão             65
Conquilha              53
Amêijoa-macha          48
Ostra-plana            31
Castanhola             28
Amêijola               15
Pé-de-burro            15
Amêijoa-relógio         9
Ostra                   8
Longueirão-direito      6
Amêijoa-asiática        4
Amêijoa-cão             4
Pé-de-burrinho          4
Vieira                  3
Taralhão                2
Pé-de burrinho          2
Zamburinha              2
Amêjoa-boa              1
Amêija-japonesa         1
Mexihão                 1
Leque                   1
Navalha                 1
Name: Espécie, dtype: int64

In [31]:
ostra=ipma9[ipma9["Espécie"]=="Ostra"]
ipma9.drop(ostra.index,inplace=True)

In [32]:
ipma9["Espécie"].value_counts()

Ostra-japonesa        237
Mexilhão              226
Ostra-portuguesa      210
Amêijoa-boa           203
Amêijoa-japonesa      152
Lambujinha            152
Berbigão              136
Amêijoa-branca         71
Longueirão             65
Conquilha              53
Amêijoa-macha          48
Ostra-plana            31
Castanhola             28
Amêijola               15
Pé-de-burro            15
Amêijoa-relógio         9
Longueirão-direito      6
Amêijoa-asiática        4
Pé-de-burrinho          4
Amêijoa-cão             4
Vieira                  3
Zamburinha              2
Taralhão                2
Pé-de burrinho          2
Amêjoa-boa              1
Amêija-japonesa         1
Mexihão                 1
Leque                   1
Navalha                 1
Name: Espécie, dtype: int64

In [33]:
ipma9.loc[ipma8["Espécie"].isin( ["Longueirão-direito"]), "Espécie"] = "Longueirão"

In [34]:
ipma9["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            226
Ostra-portuguesa    210
Amêijoa-boa         203
Lambujinha          152
Amêijoa-japonesa    152
Berbigão            136
Longueirão           71
Amêijoa-branca       71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Pé-de-burro          15
Amêijola             15
Amêijoa-relógio       9
Amêijoa-asiática      4
Pé-de-burrinho        4
Amêijoa-cão           4
Vieira                3
Zamburinha            2
Taralhão              2
Pé-de burrinho        2
Amêjoa-boa            1
Amêija-japonesa       1
Mexihão               1
Leque                 1
Navalha               1
Name: Espécie, dtype: int64

In [35]:
asiatica= ipma9[ipma9["Espécie"] == "Amêijoa-asiática"]
ipma10 = ipma9.drop(asiatica.index)

In [36]:
ipma10["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            226
Ostra-portuguesa    210
Amêijoa-boa         203
Lambujinha          152
Amêijoa-japonesa    152
Berbigão            136
Amêijoa-branca       71
Longueirão           71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Pé-de-burro          15
Amêijola             15
Amêijoa-relógio       9
Amêijoa-cão           4
Pé-de-burrinho        4
Vieira                3
Zamburinha            2
Taralhão              2
Pé-de burrinho        2
Leque                 1
Amêjoa-boa            1
Amêija-japonesa       1
Mexihão               1
Navalha               1
Name: Espécie, dtype: int64

In [37]:
zamburinha= ipma10[ipma10["Espécie"] == "Zamburinha"]
ipma11 = ipma10.drop(zamburinha.index)

In [38]:
ipma11["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            226
Ostra-portuguesa    210
Amêijoa-boa         203
Lambujinha          152
Amêijoa-japonesa    152
Berbigão            136
Longueirão           71
Amêijoa-branca       71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Pé-de-burro          15
Amêijola             15
Amêijoa-relógio       9
Pé-de-burrinho        4
Amêijoa-cão           4
Vieira                3
Taralhão              2
Pé-de burrinho        2
Leque                 1
Amêjoa-boa            1
Amêija-japonesa       1
Mexihão               1
Navalha               1
Name: Espécie, dtype: int64

In [39]:
ipma11.loc[ipma11["Espécie"].isin( ["Leque"]), "Espécie"] = "Vieira"

In [40]:
ipma11["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            226
Ostra-portuguesa    210
Amêijoa-boa         203
Lambujinha          152
Amêijoa-japonesa    152
Berbigão            136
Longueirão           71
Amêijoa-branca       71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Amêijola             15
Pé-de-burro          15
Amêijoa-relógio       9
Vieira                4
Amêijoa-cão           4
Pé-de-burrinho        4
Taralhão              2
Pé-de burrinho        2
Amêjoa-boa            1
Amêija-japonesa       1
Mexihão               1
Navalha               1
Name: Espécie, dtype: int64

In [41]:
ipma11.loc[ipma11["Espécie"].isin( ["Amêjoa-boa"]), "Espécie"] = "Amêijoa-boa"
ipma11["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            226
Ostra-portuguesa    210
Amêijoa-boa         204
Lambujinha          152
Amêijoa-japonesa    152
Berbigão            136
Longueirão           71
Amêijoa-branca       71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Amêijola             15
Pé-de-burro          15
Amêijoa-relógio       9
Vieira                4
Amêijoa-cão           4
Pé-de-burrinho        4
Taralhão              2
Pé-de burrinho        2
Amêija-japonesa       1
Mexihão               1
Navalha               1
Name: Espécie, dtype: int64

In [42]:
ipma11.loc[ipma11["Espécie"].isin( ["Amêija-japonesa"]), "Espécie"] = "Amêijoa-japonesa"
ipma11["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            226
Ostra-portuguesa    210
Amêijoa-boa         204
Amêijoa-japonesa    153
Lambujinha          152
Berbigão            136
Longueirão           71
Amêijoa-branca       71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Pé-de-burro          15
Amêijola             15
Amêijoa-relógio       9
Amêijoa-cão           4
Pé-de-burrinho        4
Vieira                4
Taralhão              2
Pé-de burrinho        2
Mexihão               1
Navalha               1
Name: Espécie, dtype: int64

In [43]:
ipma11.loc[ipma11["Espécie"].isin( ["Mexihão"]), "Espécie"] = "Mexilhão"
ipma11["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            227
Ostra-portuguesa    210
Amêijoa-boa         204
Amêijoa-japonesa    153
Lambujinha          152
Berbigão            136
Longueirão           71
Amêijoa-branca       71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Pé-de-burro          15
Amêijola             15
Amêijoa-relógio       9
Amêijoa-cão           4
Pé-de-burrinho        4
Vieira                4
Taralhão              2
Pé-de burrinho        2
Navalha               1
Name: Espécie, dtype: int64

In [44]:
ipma11.loc[ipma11["Espécie"].isin( ["Navalha"]), "Espécie"] = "Longueirão"
ipma11["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            227
Ostra-portuguesa    210
Amêijoa-boa         204
Amêijoa-japonesa    153
Lambujinha          152
Berbigão            136
Longueirão           72
Amêijoa-branca       71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Amêijola             15
Pé-de-burro          15
Amêijoa-relógio       9
Vieira                4
Amêijoa-cão           4
Pé-de-burrinho        4
Taralhão              2
Pé-de burrinho        2
Name: Espécie, dtype: int64

In [45]:
ipma11.loc[ipma11["Espécie"].isin( ["Pé-de burrinho"]), "Espécie"] = "Pé-de-burrinho"
ipma11["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            227
Ostra-portuguesa    210
Amêijoa-boa         204
Amêijoa-japonesa    153
Lambujinha          152
Berbigão            136
Longueirão           72
Amêijoa-branca       71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Amêijola             15
Pé-de-burro          15
Amêijoa-relógio       9
Pé-de-burrinho        6
Vieira                4
Amêijoa-cão           4
Taralhão              2
Name: Espécie, dtype: int64

# Tratar Dados LQ

In [46]:
LQ=ipma11[ (ipma11["Pb\n(mg/kg)"].str.contains("<",regex=False) | (ipma11["Pb\n(mg/kg)"].str.contains("LQ",regex=False, na=False)))]
LQ

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
8,1295/22,2022-12-12,EMR,Roncanito,Ostra-portuguesa,"< 0,06"
21,1126/22,2022-10-20,RIAV3,Passagem,Amêijoa-boa,< 0.06
22,1106/22,2022-10-13,L7c2,Albufeira,Conquilha,< 0.06
23,1073/22,2022-10-10,ETJ2,Baliza de Ferro,Amêijoa-japonesa,< 0.06
...,...,...,...,...,...,...
1923,14258,2015-09-01,LAG,Vale da Lama,Amêijoa-boa,"< 0,06"
1924,14259,2015-09-01,POR2,Povoação,Amêijoa-boa,"< 0,06"
1982,13542,2015-03-10,LOB,Graijau,Amêijoa-japonesa,"< 0,06"
1985,13547,2015-03-10,LAG1,Vale da Lama,Amêijoa-boa,"< 0,06"
1997,13540,2015-03-09,TAV2,Quatro Águas,Amêijoa-boa,"< 0,06"

In [47]:
LQ.to_csv("IPMA_LQ.csv")

__LQ=0.01__

In [48]:
ipma11.loc[(ipma11["Pb\n(mg/kg)"].str.contains("<",regex=False) | (ipma11["Pb\n(mg/kg)"].str.contains("LQ",regex=False, na=False))), "Pb\n(mg/kg)"]="0.01"

In [49]:
ipma11[ipma11["Pb\n(mg/kg)"]=="0.01"]

,Nº Amostra,Data de colheita,Zona de\nProdução,Local,Espécie,Pb\n(mg/kg)
0,65/23,2023-01-30,EMR,Roncanito,Ostra-portuguesa,0.01
8,1295/22,2022-12-12,EMR,Roncanito,Ostra-portuguesa,0.01
21,1126/22,2022-10-20,RIAV3,Passagem,Amêijoa-boa,0.01
22,1106/22,2022-10-13,L7c2,Albufeira,Conquilha,0.01
23,1073/22,2022-10-10,ETJ2,Baliza de Ferro,Amêijoa-japonesa,0.01
...,...,...,...,...,...,...
1923,14258,2015-09-01,LAG,Vale da Lama,Amêijoa-boa,0.01
1924,14259,2015-09-01,POR2,Povoação,Amêijoa-boa,0.01
1982,13542,2015-03-10,LOB,Graijau,Amêijoa-japonesa,0.01
1985,13547,2015-03-10,LAG1,Vale da Lama,Amêijoa-boa,0.01
1997,13540,2015-03-09,TAV2,Quatro Águas,Amêijoa-boa,0.01

In [50]:
ipma11["Espécie"].value_counts()

Ostra-japonesa      237
Mexilhão            227
Ostra-portuguesa    210
Amêijoa-boa         204
Amêijoa-japonesa    153
Lambujinha          152
Berbigão            136
Longueirão           72
Amêijoa-branca       71
Conquilha            53
Amêijoa-macha        48
Ostra-plana          31
Castanhola           28
Amêijola             15
Pé-de-burro          15
Amêijoa-relógio       9
Pé-de-burrinho        6
Vieira                4
Amêijoa-cão           4
Taralhão              2
Name: Espécie, dtype: int64

# Exportar Dados para o Excel

In [51]:
ipma11.to_csv("IPMA_Dados_Limpos_Final.csv")